-- MySQL Script generated by MySQL Workbench
-- 05/15/17 15:35:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location_id` INT NULL,
  `name` VARCHAR(255) NULL,
  `recommended_level` INT NULL,
  `type` ENUM('hunting_ground', 'instanced_dungeon', 'town', 'field') NULL,
  `has_zemyna_statue` TINYINT(1) NULL,
  `position` JSON NULL,
  `territory` ENUM('klaipeda', 'orsha', 'fedimian') NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locations_locations_idx` (`location_id` ASC),
  CONSTRAINT `fk_locations_locations`
    FOREIGN KEY (`location_id`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locations_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locations_locations` (
  `location_id` INT NOT NULL,
  `location_parent_id` INT NOT NULL,
  INDEX `fk_locations_has_locations_locations2_idx` (`location_parent_id` ASC),
  INDEX `fk_locations_has_locations_locations1_idx` (`location_id` ASC),
  PRIMARY KEY (`location_id`, `location_parent_id`),
  CONSTRAINT `fk_locations_has_locations_locations1`
    FOREIGN KEY (`location_id`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locations_has_locations_locations2`
    FOREIGN KEY (`location_parent_id`)
    REFERENCES `locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
